title: Lokesh Das
logo: /assets/img/logo.jpg
description: PhD Candidate | University of Memphis\n Department of Computer Science\nCollege Arts \& Sciences
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
